"""create system settings table

Revision ID: 229b72ef0abb
Revises: 36d11a5e3380
Create Date: 2026-08-14 15:26:55.009742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229b72ef0abb'
down_revision: Union[str, Sequence[str], None] = '36d11a5e3380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_percentage', sa.Integer(), nullable=False),
    sa.Column('cancellation_window_hours', sa.Integer(), nullable=False),
    sa.Column('reservation_charge_per_hour_per_guest', sa.Integer(), nullable=False),
    sa.Column('food_bill_threshold', sa.Integer(), nullable=False),
    sa.Column('food_addition_cutoff_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
