"""add refund id

Revision ID: 36d11a5e3380
Revises: 6144f0a1ce29
Create Date: 2026-08-13 14:59:35.259470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d11a5e3380'
down_revision: Union[str, Sequence[str], None] = '6144f0a1ce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('refund_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'refund_id')
    # ### end Alembic commands ###
