RESERVATION_CHARGE_PER_HOUR_PER_GUEST = 20

FOOD_BILL_THRESHOLD = 1000

REFUND_PERCENTAGE = 80

FOOD_ADDITION_CUTOFF_MINUTES = 30
CANCELLATION_WINDOW_HOURS = 1
#reservation status constants
MINIMUM_RESERVATION_DURATION_HOURS = 1
PENDING_PAYMENT = "PENDING_PAYMENT"
CONFIRMED = "CONFIRMED"
ACTIVE = "ACTIVE"
COMPLETED = "COMPLETED"
CANCELLED = "CANCELLED"
EXPIRED = "EXPIRED"
#order status constants
ORDER_PENDING = "PENDING"
ORDER_CONFIRMED = "CONFIRMED"
ORDER_PREPARING = "PREPARING"
ORDER_READY = "READY"
ORDER_SERVED = "SERVED"
ORDER_COMPLETED = "COMPLETED"
ORDER_CANCELLED = "CANCELLED"
#payment status constants
PAYMENT_PENDING = "PENDING"
PAYMENT_PAID = "PAID"
PAYMENT_FAILED = "FAILED"
PAYMENT_REFUNDED = "REFUNDED"
REFUND_NOT_APPLICABLE = "NOT_APPLICABLE"
REFUND_PENDING = "PENDING"
REFUND_COMPLETED = "COMPLETED"

USER_ROLE = "USER"
ADMIN_ROLE = "ADMIN"